export const EVENT = {
  AI_SEVERE_WEATHER_OUTLOOK_SUMMARY_GENERATED:
    'AI_SEVERE_WEATHER_OUTLOOK_SUMMARY_GENERATED',
  AI_SEVERE_WEATHER_OUTLOOK_SUMMARY_GENERATING:
    'AI_SEVERE_WEATHER_OUTLOOK_SUMMARY_GENERATING',
  AI_THUNDERSTORM_OUTLOOK_SUMMARY_GENERATED:
    'AI_THUNDERSTORM_OUTLOOK_SUMMARY_GENERATED',
  AI_THUNDERSTORM_OUTLOOK_SUMMARY_GENERATING:
    'AI_THUNDERSTORM_OUTLOOK_SUMMARY_GENERATING',
  ISSUED_ALERTS_UPDATING: 'ISSUED_ALERTS_UPDATING',
  SEVERE_WEATHER_OUTLOOK_UPDATING: 'SEVERE_WEATHER_OUTLOOK_UPDATING',
  THUNDERSTORM_OUTLOOK_UPDATING: 'THUNDERSTORM_OUTLOOK_UPDATING',
  ISSUED_ALERTS_UPDATED: 'ISSUED_ALERTS_UPDATED',
  SEVERE_WEATHER_OUTLOOK_UPDATED: 'SEVERE_WEATHER_OUTLOOK_UPDATED',
  THUNDERSTORM_OUTLOOK_UPDATED: 'THUNDERSTORM_OUTLOOK_UPDATED',
};
