export const Event = {
  AI_SEVERE_WEATHER_OUTLOOK_SUMMARY_GENERATED:
    'AI_SEVERE_WEATHER_OUTLOOK_SUMMARY_GENERATED',
  AI_SEVERE_WEATHER_OUTLOOK_SUMMARY_GENERATING:
    'AI_SEVERE_WEATHER_OUTLOOK_SUMMARY_GENERATING',
  AI_THUNDERSTORM_OUTLOOK_SUMMARY_GENERATED:
    'AI_THUNDERSTORM_OUTLOOK_SUMMARY_GENERATED',
  AI_THUNDERSTORM_OUTLOOK_SUMMARY_GENERATING:
    'AI_THUNDERSTORM_OUTLOOK_SUMMARY_GENERATING',
};
