/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as AlertIndexRouteImport } from './routes/alert/index'
import { Route as AblyCreateTokenRouteImport } from './routes/ably/create-token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertIndexRoute = AlertIndexRouteImport.update({
  id: '/alert/',
  path: '/alert/',
  getParentRoute: () => rootRouteImport,
} as any)
const AblyCreateTokenRoute = AblyCreateTokenRouteImport.update({
  id: '/ably/create-token',
  path: '/ably/create-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ably/create-token': typeof AblyCreateTokenRoute
  '/alert/': typeof AlertIndexRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ably/create-token': typeof AblyCreateTokenRoute
  '/alert': typeof AlertIndexRoute
  '/search': typeof SearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ably/create-token': typeof AblyCreateTokenRoute
  '/alert/': typeof AlertIndexRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ably/create-token' | '/alert/' | '/search/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ably/create-token' | '/alert' | '/search'
  id: '__root__' | '/' | '/ably/create-token' | '/alert/' | '/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AblyCreateTokenRoute: typeof AblyCreateTokenRoute
  AlertIndexRoute: typeof AlertIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert/': {
      id: '/alert/'
      path: '/alert'
      fullPath: '/alert/'
      preLoaderRoute: typeof AlertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ably/create-token': {
      id: '/ably/create-token'
      path: '/ably/create-token'
      fullPath: '/ably/create-token'
      preLoaderRoute: typeof AblyCreateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AblyCreateTokenRoute: AblyCreateTokenRoute,
  AlertIndexRoute: AlertIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
